# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n\rPasswordCheck\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x11\n\tencrypted\x18\x02 \x01(\t\"(\n\x15\x43heckPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x08PageInfo\x12\x0e\n\x06pageNo\x18\x01 \x01(\r\x12\x10\n\x08pageSize\x18\x02 \x01(\r\"\x1f\n\rMobileRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"D\n\x0e\x43reateUserInfo\x12\x10\n\x08nickName\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\"P\n\x0eUpdateUserInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08\x62irthday\x18\x04 \x01(\x04\"\x82\x01\n\x10UserInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x10\n\x08nickName\x18\x04 \x01(\t\x12\x10\n\x08\x62irthday\x18\x05 \x01(\x04\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\x05\"B\n\x10UserListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.UserInfoResponse2\xb9\x02\n\x04User\x12+\n\x0bGetUserList\x12\t.PageInfo\x1a\x11.UserListResponse\x12\x34\n\x0fGetUserByMobile\x12\x0e.MobileRequest\x1a\x11.UserInfoResponse\x12,\n\x0bGetUserById\x12\n.IdRequest\x1a\x11.UserInfoResponse\x12\x30\n\nCreateUser\x12\x0f.CreateUserInfo\x1a\x11.UserInfoResponse\x12\x35\n\nUpdateUser\x12\x0f.UpdateUserInfo\x1a\x16.google.protobuf.Empty\x12\x37\n\rCheckPassword\x12\x0e.PasswordCheck\x1a\x16.CheckPasswordResponseB\tZ\x07.;protob\x06proto3')



_PASSWORDCHECK = DESCRIPTOR.message_types_by_name['PasswordCheck']
_CHECKPASSWORDRESPONSE = DESCRIPTOR.message_types_by_name['CheckPasswordResponse']
_PAGEINFO = DESCRIPTOR.message_types_by_name['PageInfo']
_MOBILEREQUEST = DESCRIPTOR.message_types_by_name['MobileRequest']
_IDREQUEST = DESCRIPTOR.message_types_by_name['IdRequest']
_CREATEUSERINFO = DESCRIPTOR.message_types_by_name['CreateUserInfo']
_UPDATEUSERINFO = DESCRIPTOR.message_types_by_name['UpdateUserInfo']
_USERINFORESPONSE = DESCRIPTOR.message_types_by_name['UserInfoResponse']
_USERLISTRESPONSE = DESCRIPTOR.message_types_by_name['UserListResponse']
PasswordCheck = _reflection.GeneratedProtocolMessageType('PasswordCheck', (_message.Message,), {
  'DESCRIPTOR' : _PASSWORDCHECK,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:PasswordCheck)
  })
_sym_db.RegisterMessage(PasswordCheck)

CheckPasswordResponse = _reflection.GeneratedProtocolMessageType('CheckPasswordResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPASSWORDRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:CheckPasswordResponse)
  })
_sym_db.RegisterMessage(CheckPasswordResponse)

PageInfo = _reflection.GeneratedProtocolMessageType('PageInfo', (_message.Message,), {
  'DESCRIPTOR' : _PAGEINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:PageInfo)
  })
_sym_db.RegisterMessage(PageInfo)

MobileRequest = _reflection.GeneratedProtocolMessageType('MobileRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOBILEREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:MobileRequest)
  })
_sym_db.RegisterMessage(MobileRequest)

IdRequest = _reflection.GeneratedProtocolMessageType('IdRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:IdRequest)
  })
_sym_db.RegisterMessage(IdRequest)

CreateUserInfo = _reflection.GeneratedProtocolMessageType('CreateUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserInfo)
  })
_sym_db.RegisterMessage(CreateUserInfo)

UpdateUserInfo = _reflection.GeneratedProtocolMessageType('UpdateUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERINFO,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserInfo)
  })
_sym_db.RegisterMessage(UpdateUserInfo)

UserInfoResponse = _reflection.GeneratedProtocolMessageType('UserInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERINFORESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserInfoResponse)
  })
_sym_db.RegisterMessage(UserInfoResponse)

UserListResponse = _reflection.GeneratedProtocolMessageType('UserListResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERLISTRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserListResponse)
  })
_sym_db.RegisterMessage(UserListResponse)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _PASSWORDCHECK._serialized_start=43
  _PASSWORDCHECK._serialized_end=95
  _CHECKPASSWORDRESPONSE._serialized_start=97
  _CHECKPASSWORDRESPONSE._serialized_end=137
  _PAGEINFO._serialized_start=139
  _PAGEINFO._serialized_end=183
  _MOBILEREQUEST._serialized_start=185
  _MOBILEREQUEST._serialized_end=216
  _IDREQUEST._serialized_start=218
  _IDREQUEST._serialized_end=241
  _CREATEUSERINFO._serialized_start=243
  _CREATEUSERINFO._serialized_end=311
  _UPDATEUSERINFO._serialized_start=313
  _UPDATEUSERINFO._serialized_end=393
  _USERINFORESPONSE._serialized_start=396
  _USERINFORESPONSE._serialized_end=526
  _USERLISTRESPONSE._serialized_start=528
  _USERLISTRESPONSE._serialized_end=594
  _USER._serialized_start=597
  _USER._serialized_end=910
# @@protoc_insertion_point(module_scope)
